### ISSUE TITLE
HTTP analyzer

### ISSUE THREAD

**Issue by szepeviktor** [4ley/querywall#1]
You might be interested in this
https://github.com/szepeviktor/wordpress-fail2ban/blob/master/block-bad-requests/wp-fail2ban-bad-request-instant.inc.php

And some WordPress-specific events:
https://github.com/szepeviktor/wordpress-fail2ban/blob/master/mu-plugin/wp-fail2ban-mu-instant.php#L87

**Comment by 4ley** [comment]
Definitely interesting, but what kind of functionality specifically do you want to be included into QueryWall?

**Comment by szepeviktor** [comment]
Actually none.

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
